'''
Constants will be used in the program, API connections and more
'''


from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET, STARKWARE_PERPETUALS_CONTRACT
from decouple import config


# !!! SELECT MODE !!!
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated Pairs
FIND_COINTEGRATED_PAIRS = False
# Place Trades
PLACE_TRADES = True

# Manage Exits
MANAGE_EXITS = True


# Resolution
# RESOLUTION = "1HOUR"
RESOLUTION = "15MINS"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 100
USD_MIN_COLLATERAL = 3600

# WIERD FACTOR FOR SOME TOKENS
TOKEN_FACTOR_10 = ["XLM-USD","DOGE-USD","TRON-USD"]

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

# Etheurem Adress
ETHERUEM_ADDRESS = "0xf2351fc91d9f4D61d391B4F82750Bb89C337e7A3"

# WALLET PRIVATE KEY
ETH_PRIVATE_KEY = "0x293c679c0675ba7b218bfe73d73f912229cf52a5b44f5a130bdb02ee3b785fb9"

# KEYS - Production
# Must to be on Mainnet on DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("DYDX_API_KEY_MAINNET")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# # KEYS - Development
# # Must to be on Testnet on DYDX - Goerli
# STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
# DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
# DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
# DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - Development
# Must to be on Testnet on DYDX - Sepolia
STARK_PRIVATE_KEY_SEPOLIA = config("STARK_PRIVATE_KEY_SEPOLIA")
DYDX_API_KEY_SEPOLIA = config("DYDX_API_KEY_SEPOLIA")
DYDX_API_SECRET_SEPOLIA = config("DYDX_API_SECRET_SEPOLIA")
DYDX_API_PASSPHRASE_SEPOLIA = config("DYDX_API_PASSPHRASE_SEPOLIA")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_SEPOLIA
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_SEPOLIA
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_SEPOLIA
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_SEPOLIA

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_SEPOLIA

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/vx9gB8f6m4Ki8ZyQ2oOx0sgc2xmK5T0l"
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/B_-Q59IGMvJ9UGOn-v2EfO2LO4tt7hu5"
HTTP_PROVIDER_SEPOLIA = "https://eth-sepolia.g.alchemy.com/v2/H6jt6kpmNMKH3VK5C4HmqYjXimnyi89P"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_SEPOLIA
